// Shared "does this generated page exist?" check. Dev/prod static hosting
// 200s unknown paths with the SPA shell, so existence is confirmed by
// sniffing the response body for a known generated-page marker.

const _existsCache = new Map()

export function markKnownUrls(domain, files) {
  files.forEach(f => {
    const url = `${import.meta.env.BASE_URL}domains/${encodeURIComponent(domain)}/${f.file}`
    _existsCache.set(url, true)
  })
}

export async function checkExists(url) {
  if (_existsCache.has(url)) return _existsCache.get(url)
  try {
    const res = await fetch(url)
    if (!res.ok) { _existsCache.set(url, false); return false }
    const text = await res.text()
    const exists = text.includes('spl-credit') || text.includes('Generated by')
    _existsCache.set(url, exists)
    return exists
  } catch (_) { _existsCache.set(url, false); return false }
}

export function clearExistsCache() {
  _existsCache.clear()
}
